### ISSUE TITLE
Change the text language

### ISSUE THREAD

**Issue by ziceptor** [Nocturne123/QuestionsTime#1]
add message.conf

**Comment by AlexandreArcil** [comment]
It's already planned ;)
See the to-do list in the Ore page : https://ore.spongepowered.org/Nocturne123/QuestionsTime/pages/Home#to-do

**Comment by ziceptor** [comment]
I saw. Trying to force the issue. ;)

**Comment by AlexandreArcil** [comment]
Oh ok, that's cool because I didn't know what feature to add first !
