### ISSUE TITLE
Un bug étrange ?

### ISSUE THREAD

**Issue by Mentalys** [Nocturne123/QuestionsTime#3]
De temps à autres, j'ai ça qui arrive dans mon chat ... Je crois que c'est pas normal ? :3 https://cdn.discordapp.com/attachments/186940328014512138/597200746559176799/unknown.png

**Comment by AlexandreArcil** [comment]
Prend la dernière version, la manière de gérer les composants (dont le temps) on complètement changé, peut-être que cela va réglé le problème.

**Comment by Mentalys** [comment]
Effectivement j'avais pas vu qu'une nouvelle version était sortie hier T_T J'ai mit à jour, j'indiquerai sur ce poste si le bug revient ^^

**Comment by Mentalys** [comment]
Bon alors ... y'a plus le message bizarre, mais niveau spam ... bah c'est vraiment pas mieux xD
https://cdn.discordapp.com/attachments/186940328014512138/597376854533603328/unknown.png

**Comment by AlexandreArcil** [comment]
Bug corrigé dans la version 1.1.4 : https://ore.spongepowered.org/Nocturne123/QuestionsTime/versions/1.1.4

**Comment by Mentalys** [comment]
Je confirme, bug bien corrigé, mais un nouveau est apparut xD

https://cdn.discordapp.com/attachments/186940328014512138/597763807288229889/unknown.png

**Comment by Mentalys** [comment]
Ok je viens de me rendre compte que j'avais dit qu'il y avait un bug sans expliquer xD
Là on voit que le joueurs a répondu qt>1 ... Le problème c'est que dans la config j'ai mit le personal answer à true ... x)

**Comment by AlexandreArcil** [comment]
C'est pense que c'est dû à une mauvaise orthographe dans la config, change ``personnalAnswer`` par ``personalAnswer``.
Je vais corriger ce problème ainsi que l'autre que tu m'as envoyer.

**Comment by Mentalys** [comment]
Et malheureusement ça ne fonctionne toujours pas :c https://cdn.discordapp.com/attachments/186940328014512138/599963982136213522/unknown.png

**Comment by AlexandreArcil** [comment]
Je regarderai ça samedi au plus tard !

**Comment by AlexandreArcil** [comment]
Chez moi ça a fonctionné de changer ``personnalAnswer=true`` par ``personalAnswer=true``.
Quoi qu'il en soit, j'ai corrigé le mot dans la config par défaut et le message doublé du timer.

Bugs corrigé dans la version 1.1.5

**Comment by Mentalys** [comment]
Alors ... Je n'ai aucune idée de pourquoi, mais malgré la nouvelle version ... https://cdn.discordapp.com/attachments/573243793424384000/602177887793184778/unknown.png

Je rajoute le fichier de config, je vois vraiment pas ce que j'ai faut comme bêtise :/
[config.zip](https://github.com/Nocturne123/QuestionsTime/files/3413807/config.zip)
