### ISSUE TITLE
Un système de rareté des questions ?

### ISSUE THREAD

**Issue by Mentalys** [Nocturne123/QuestionsTime#4]
It's me again ! x)

Rajouter un niveau de rareté aux questions serait cool, j'aimerais bien mettre des questions qui donnent des chosent précieuses, mais si elles tombent souvent ... j'vais ruiner l'économie de mon serveur ... est-ce que ce serait possible ? :3

**Comment by AlexandreArcil** [comment]
Je trouve que c'est une bonne idée, mais il reste à définir les niveaux de rareté, et un visuel pour connaitre la rareté d'une question.

**Comment by Mentalys** [comment]
Une option "rarity=" et on met un chiffre ? Le plugin compare ensuite toutes les valeur et sort plus souvent celles qui ont un chiffre élevé ?

**Comment by AlexandreArcil** [comment]
Oui, mais je demandais le nombre de niveaux de rareté ? A moins qu'il n'en a pas vraiment, et que cela ressemble à un système de poids ?

**Comment by Mentalys** [comment]
L'avantage du système de poids c'est qu'on peut le personnaliser comme on veut ^^

**Comment by AlexandreArcil** [comment]
Ok donc on part sur un système de poids ?
Aura-t-il un visuel pour représenter ce poids ? Si oui, lequel ?

**Comment by Mentalys** [comment]
Un visuel ? C'est à dire ? Pour que les joueurs voient la rareté ? Mouais, je sais pas si c'est utile, comme tu le sens :3

**Comment by AlexandreArcil** [comment]
Ok donc va pour un système de poids !
