### ISSUE TITLE
Chat Bugs

### ISSUE THREAD

**Issue by bleihof** [Nocturne123/QuestionsTime#5]
I found the following bug:

With me is in the chat with each you win, even with the one who won nothing. It happens that he did not win, player xyz won.

The one who did not win:
https://puu.sh/E4n5l/a77593f907.png
Who won where:
https://puu.sh/E4n5D/5bbe01c887.png

In addition I have set in the config the message should not be sent in the public chat.
https://puu.sh/E4ncA/26a881cec2.png
As you can see above with the scrennshots it will be anyway.

I use the latest version of the questions plugin.
Sponge Version: spongeforge-1.12.2-2825-7.1.6-RC3716

**Comment by AlexandreArcil** [comment]
If I have understood correctly,  ``personalAnswer`` doesn't work and the message ``You win`` is send to everybody ?
I will check !

**Comment by AlexandreArcil** [comment]
Ok I solved the first bug but I didn't achieved to reproduce the second
https://image.noelshack.com/fichiers/2019/33/3/1565786923-capture.png
(it's 2 Minecraft opened on the same server, with the same sponge forge version than you)
Can you give me your config.conf please ? (without the questions if you want)

**Comment by bleihof** [comment]
Have actually the standard config. The only thing I've changed is the cooldowns, so every minute there is a question to test.
I have other plugins on it but I have previously disabled all times. But bug is still coming.

Here are the desired files.

https://puu.sh/E5brt/5360e956af.png
https://puu.sh/E5brQ/64e5de3a94.png

**Comment by AlexandreArcil** [comment]
hum... I made a little change. I will post a beta version today if I can, or tomorrow.

**Comment by AlexandreArcil** [comment]
I didn't know why but I can't create a new channel. The first time, Ore said he has an error. The second time, the channel isn't created. I will post the plugin later if I can, sunday otherwise.

**Comment by AlexandreArcil** [comment]
I posted the new version. If the bug is still here, please send the debug.log. If not, I will close this issue and start to add new feature !

**Comment by bleihof** [comment]
I will test it today or at the latest tomorrow

**Comment by bleihof** [comment]
The Chatausgabe who wins votes. But the message the other player wrote is still in the chat.

Where can I send the debug.log, I do not want to be here, do not want that everyone has it.

**Comment by AlexandreArcil** [comment]
You can't send a private message in Github, so what you can do is to send me only the lines which contains ``[questionstime]``.

**Comment by bleihof** [comment]
Will not be able to send it before Sunday.

**Comment by AlexandreArcil** [comment]
Ok. The bug where messages were sent in the chat even if it was disabled in the config is still present in your side ? An other person had this bug and it was fixed in the version 1.1.6.

**Comment by bleihof** [comment]
With the version 1.1.6 I had the bug still. I test it again on Sunday and send the logs if it would not work again.

**Comment by AlexandreArcil** [comment]
Is the bug still relevant ?
