### ISSUE TITLE
Mauvais gagnant indiqué

### ISSUE THREAD

**Issue by Mentalys** [Nocturne123/QuestionsTime#6]
Bonjour ça fait un moment o/

C'est bon, les réponses sont enfin cachées ! Par contre y'a un soucis, le message dit que "XXXX win !" ne prend pas en compte le pseudo du gagnant mais le pseudo de notre personnage (Moi je lis Mentalys, un de mes admins lit son propre pseudo etc ...)

Merci pour la mise à jour, là déjà même si y'a encore ce petit bug je vais pouvoir faire tourner le plugin sur mon serveur <3

**Comment by AlexandreArcil** [comment]
Corrigé dans la dernière version.
Du coup je peux fermer l'autre issue ?

**Comment by Mentalys** [comment]
J'ai pu vérifier, tout à l'air de fonctionner (enfin j'ai pas encore testé le système de poids mais si y'a un soucis je me ferai un plaisir de rouvrir un ticket xD)

Bien joué et merci !

**Comment by AlexandreArcil** [comment]
Cool ! Et merci à toi de reporter ce genre de bug. Il sont surtout arrivé dû au fait que je n'essayais le plugin que tout seul sur un serveur.
