### ISSUE TITLE
Config keeps deleting questions I add

### ISSUE THREAD

**Issue by CommanderLouiz** [Nocturne123/QuestionsTime#8]
Title

It seems that for whatever reason, anytime I have more than two questions in the config file, a random one (or more) gets deleted without warning.

I've only added them directly via the configs, not in-game via the command.

QT version = 1.1.7 (Most Recent)
Minecraft Version = 1.12.2
Sponge Version = 1.12.2-2838-7.2.1-RC4011
Modpack = Lapito's Galacticraft

**Comment by AlexandreArcil** [comment]
Hello,
Can you post the logs and the config file of Questions Time please.

**Comment by CommanderLouiz** [comment]
[configOriginal.txt](https://github.com/Nocturne123/QuestionsTime/files/4927892/configOriginal.txt)
[configAfter.txt](https://github.com/Nocturne123/QuestionsTime/files/4927931/configAfter.txt)


[2020-07-15-6.log.gz](https://github.com/Nocturne123/QuestionsTime/files/4929348/2020-07-15-6.log.gz)
_Extract with 7-Zip_
[debug-3.log.gz](https://github.com/Nocturne123/QuestionsTime/files/4929355/debug-3.log.gz)

On first look, doesn't seem to be any mention in there of deleting a question, it just only loads two.

**Comment by AlexandreArcil** [comment]
The config has two questions with the same name, and Hocon seems to load only one. I think I can't do something, it's a Hocon issue.

**Comment by CommanderLouiz** [comment]
So you're saying "simplequestion" and"multiplequestion" are the names of the questions, and not an identifier used to determine if they're multiple choice or not?

**Comment by CommanderLouiz** [comment]
It would seem that that is the case, as I added a third question, named it "ques2n" and after a restart, it still exists, though its place was moved around in the config.

**Comment by AlexandreArcil** [comment]
Yes, it's a "name" / a "identifier", not the question type.
